apiVersion: v1
kind: Service
metadata:
  name: nuit-one-api
  namespace: nuit-one
spec:
  type: ClusterIP
  selector:
    app: nuit-one-api
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
