apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nuit-one
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:6666e241265144067706472ceac0f318c0212c280774ddb198637a608d4431f3
  name: ghcr.io/madfam-org/nuit-one/api
  newName: ghcr.io/madfam-org/nuit-one/api
- digest: sha256:7eed3287cc7ddd3ea9c593dadb22b3dbc9d846c2daa3d6414028858db3473193
  name: ghcr.io/madfam-org/nuit-one/web
  newName: ghcr.io/madfam-org/nuit-one/web
