apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nuit-one
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:d176fba695344d5bff4d5753afdfacffebff7b6d77e2c4add2c8885395838c6b
  name: ghcr.io/madfam-org/nuit-one/api
  newName: ghcr.io/madfam-org/nuit-one/api
- digest: sha256:f2df2fe10e875f494f423d5bd8b8af31780c148f922397a765bcdeb1b29b4985
  name: ghcr.io/madfam-org/nuit-one/web
  newName: ghcr.io/madfam-org/nuit-one/web
