apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nuit-one
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- name: ghcr.io/madfam-org/nuit-one/api
  newName: ghcr.io/madfam-org/nuit-one/api
- name: ghcr.io/madfam-org/nuit-one/web
  newName: ghcr.io/madfam-org/nuit-one/web
